name: Build & Push FilWizard (Smart contract deployment tool).

on:
  workflow_dispatch:
    inputs:
      filwizard_tag:
        type: string
        required: true
        default: 'latest'
        description: A filwizard tag

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Antithesis Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.ANTITHESIS_GAR_KEY }}

    - name: Extract metadata (tags) for Docker filwizard
      id: meta-filwizard
      uses: docker/metadata-action@v5
      with:
        images: us-central1-docker.pkg.dev/molten-verve-216720/filecoin-repository/filwizard
        tags: |
          type=sha
          ${{ github.event.inputs.filwizard_tag }}
    - name: Build and push filwizard
      uses: docker/build-push-action@v5
      with:
        context: ./filwizard
        file: ./filwizard/Dockerfile
        push: true
        tags: ${{ steps.meta-filwizard.outputs.tags }}, ${{ env.GITHUB_REF_NAME }}
        labels: ${{ steps.meta-filwizard.outputs.labels }}
