name: Build & Push Forest

on:
  schedule:
    # 6 PM EST, Mon & Thurs
    - cron: '0 22 * * 1'
  workflow_dispatch:
    inputs:
      forest_commit:
        type: string
        required: true
        default: '9ae9c64'
        description: A commit hash that can be found from (https://github.com/ChainSafe/forest)
  workflow_call:
    inputs:
      forest_commit:
        type: string
        required: true
        description: A commit hash from (https://github.com/ChainSafe/forest)
    secrets:
      ANTITHESIS_GAR_KEY:
        required: true

jobs:
  antithesis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Check disk before cleanup
      run: df -h

    - name: Node cleanup
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a --force

    - name: Check disk after cleanup
      run: df -h
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Antithesis Google Artifact Registry
      uses: docker/login-action@v3
      with:
        # These secrets would need to be populated in your repo and named
        # this way if you want to copy-and-paste this configuration.
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.ANTITHESIS_GAR_KEY }}

    # scheduled Monday nights 6pm est
    - name: Get latest forest commit hash
      if: github.event_name == 'schedule'
      id: latest-forest-commit
      run: echo "commit-hash=$(git ls-remote https://github.com/ChainSafe/forest.git HEAD | cut -f1)" >> $GITHUB_OUTPUT

    # There is a lot of copy-and-paste in these sections.
    # This could be streamlined by using a matrix configuration, which would
    # parameterize the extract and build stages. However, it would run both the
    # setup and teardown sections N times, once for each of the N containers we
    # are going to build and deploy.
    - name: Extract metadata (tags) for Docker forest
      id: meta-forest
      uses: docker/metadata-action@v5
      with:
        images: us-central1-docker.pkg.dev/molten-verve-216720/filecoin-repository/forest
        tags: |
            type=sha
            ${{ inputs.forest_commit || steps.latest-forest-commit.outputs.commit-hash }}
            latest
    - name: Build and push forest
      uses: docker/build-push-action@v5
      with:
        build-args: |
            GIT_COMMIT=${{ inputs.forest_commit || steps.latest-forest-commit.outputs.commit-hash }}
            LOCAL_BUILD=0
        context: ./forest
        file: ./forest/Dockerfile
        push: true
        tags: ${{ steps.meta-forest.outputs.tags }}
        labels: ${{ steps.meta-forest.outputs.labels }}